### ISSUE TITLE
Document backup procedures

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/documentation#10]
I would be beneficial to have an official description of how to backup the graylog configuration that is persisted into mongodb ...

**Comment by jalogisch** [comment]
@henrikjohansen did you worked out your backup already? can you describe?

**Comment by henrikjohansen** [comment]
We dump the mongo db as suggested. I would still like to see something like that build into Graylog as a system job (ie. daily dumps of the configuration in mongo to a file with configurable interval and retention). 

I do not entirely agree with your comments in commit ce6ed82 - when it comes to a **configuration** backup there really only is one way to do so (every system is not special in that regard).

**Comment by jalogisch** [comment]
hej @henrikjohansen i can see your point. 

In your point of view, adding something like https://github.com/micahwedemeyer/automongobackup and give graylog this function as plugin or in core would be recommend?

**Comment by henrikjohansen** [comment]
Absolutely, yes.

**Comment by jalogisch** [comment]
we have the server issue to create backup plugin or similar we do not need to have this issue open in the documentation. 

This task is very specific and the notes already in the docs are sufficient.
