### ISSUE TITLE
Typo in (missing set-external-ip command)

### ISSUE THREAD

**Issue by 123dev** [Graylog2/documentation#100]
In section
https://github.com/Graylog2/documentation/blob/f9076e3460a39fe3e3d5a59d8a294afc522d2053/pages/installation/aws.rst#https

`sudo graylog-ctl https://<public ip>:443/api`

Should be

`sudo graylog-ctl set-external-ip https://<public ip>:443/api`

Also would be nice to specify if it could be a hostname instead of the IP or not.

**Comment by joschi** [comment]
This has already been fixed in #97.
