### ISSUE TITLE
Be more specific about the elasticsearch 7 version

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/documentation#1047]
## Context
As here https://github.com/Graylog2/graylog2-server/issues/9706#issuecomment-762048226 makes it visible that we need to be more specific WHAT Elasticsearch version is supported and what is the lowest possible version for ES7. 

## Expected Content
Have clear statements on pages like: https://docs.graylog.org/en/4.0/pages/installation.html about the ES7 version and check all other parts of the docs for such possible additions to be more clear to users.

**Comment by dennisoelkers** [comment]
The initial idea was that we support _all_ 7.x versions, because the underlying issue of #9706 was not documented very well in the ES release notes. So the earlies 7.x version we do support is 7.7.0. For 6.x, the information is accurated (supporting 6.8+).

**Comment by jalogisch** [comment]
fixed with https://github.com/Graylog2/documentation/pull/1079
