### ISSUE TITLE
broken link on marketplace footer

### ISSUE THREAD

**Issue by Nothing4You** [Graylog2/documentation#1052]
this isn't a docs issue but I couldn't find an alternative place to put this besides contacting the marketing department.

on https://marketplace.graylog.org the footer link `Contact` points to https://www.graylog.org/pages/contact_form which redirects to https://go.graylog.com/contact-us which is NXDOMAIN

**Comment by jalogisch** [comment]
thank you for this report @Nothing4You I'll pick that up and see that we can solve that as quickly as possible.

**Comment by bernd** [comment]
This has been fixed. Thanks for the report!
