### ISSUE TITLE
Elaborate on bigger production setups

### ISSUE THREAD

**Issue by terwey** [Graylog2/documentation#106]
Currently the documentation doesn't explain how to actually setup a multi-node environment using Graylog v2.

I've made a small patch for the docs here: https://github.com/Graylog2/documentation/pull/105

However it would be good if someone could elaborate that is more knowledgeable about the subject.

**Comment by jalogisch** [comment]
this should include information that need to be set as in https://github.com/Graylog2/graylog2-server/issues/2360 written. 

we need to get information how common setups are in _the wild_. we only know those that we can think of or that makes sense for us. but that might not be the real pain.

what does your setup look like @terwey

**Comment by jalogisch** [comment]
This is more common than i though https://github.com/Graylog2/graylog2-server/issues/384

need to fix this in the docs

**Comment by jalogisch** [comment]
we added https://github.com/Graylog2/documentation/pull/128 for now this is the starting point on this.

please create a new issue if you like to have a section with more / additional information
