### ISSUE TITLE
There is no standard extractor

### ISSUE THREAD

**Issue by Comradin** [Graylog2/documentation#109]
Hello,

the documentation at http://docs.graylog.org/en/2.0/pages/extractors.html#the-standard-date-converter
speaks of using a standard extractor rule to extract the time from a log line, but there is no standard extractor.

There are the following ones:
- Copy input
- Grok pattern
- JSON
- Regular Expression
- Replace with regular expression
- Split & Index
- Substring

Which one is/was the standard one?

**Comment by edmundoa** [comment]
Hi,

The documentation describes the standard date converter, not extractor. You can add converters to most extractors to modify the outcome of said extractor.

Please ask in our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog) if you have any further questions.

Thank you!

**Comment by Comradin** [comment]
Hi, I asked this questin on irc and got the advice to open a ticket for further clarification ;)

**Comment by edmundoa** [comment]
Didn't know about that, reopening :)

**Comment by jalogisch** [comment]
@edmundoa when you look at this sentence:

> Use a standard extractor rule to select the timestamp and apply the Date converter with a format string

that does not make sense in as @Comradin already pointed out!

**Comment by jalogisch** [comment]
i had modified the documentation now it should be clear
