### ISSUE TITLE
Documentation doesn't have the links for 4.2 installation

### ISSUE THREAD

**Issue by Sirclicksalot** [Graylog2/documentation#1219]
## Context
Graylog raises an alert that the current running version isn't the latest of 4.2, but the installation instructions only point to the `wget https://packages.graylog2.org/repo/packages/graylog-4.1-repository_latest.deb` source.
## Goal
To follow docs to upgrade and remove warning in Graylog web console
## Expected Content
URL in the docs to point to `wget https://packages.graylog2.org/repo/packages/graylog-4.1-repository_latest.deb`, or the alert to hold back until docs are updated so that there are clear instructions as to how to remove warning without having to go hunting on https://packages.graylog2.org/

## Your Environment
Ubuntu 18.04

* Graylog Version: 4.1.6
* Elasticsearch Version: 7.9 (AWS)
* MongoDB Version: 4.4.9

**Comment by dulanism** [comment]
Hi, @Sirclicksalot. Thanks for catching this. Can you confirm the changes are updated on this page? https://docs.graylog.org/docs/ubuntu

**Comment by Sirclicksalot** [comment]
Looks great! 👍🤘 Thanks for the update.

*Edit* and I appreciate you not calling me out on the fact that I copy and pasted the wrong URL in the expected results section above. ¯\(°_o)/¯
