### ISSUE TITLE
Add section in "Sending in log data" about rsyslog inputs over tls

### ISSUE THREAD

**Issue by lhyx** [Graylog2/documentation#126]
Hi,

I can't find any documentation about how to send in log data via rsyslog over tls. Do rsyslog inputs require the same type of certificates as the web interface ?
How does rsyslog need to be configured ?

Thanks in advance.

**Comment by joschi** [comment]
@lhyx The syslog inputs (or in general any TCP-based input with TLS support) in Graylog require the same format (X.509 certificates and PKCS#8 private keys in PEM format) like the web interface (`web_tls_*`) and REST API listeners (`rest_tls_*`).

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
