### ISSUE TITLE
Document all server.conf config options

### ISSUE THREAD

**Issue by Comradin** [Graylog2/documentation#133]
Hello,

I've been looking for a more detailed explanation for these two config options:
rest_thread_pool_size
rest_worker_threads_max_pool_size

But searching for these options finds nothing in the documentation.

I had some performance trouble and tried to raise these values, but without a thorough background what each option will configure in the graylog server, Im not sure, if I have configured proper values.

**Comment by martinbydefault** [comment]
I'm willing to document all the server configuration options.  
My idea is to create a new page named **server.conf** in the [**Configuring Graylog**](http://docs.graylog.org/en/latest/pages/configuration.html#) section, listing all the parameters from the `server.conf` file and also include deprecated options (options that now are managed from the web interface and stored in mogodb) to have all them in a single place documented (easier than reading all the release notes and changelogs).  
  
My idea is to first copy all the descriptions that are in the `server.conf` file and also all the info that it's already in the documentation.  
Then I will try to find some extra information about the options that are poorly documented, giving priority to sources that are official or similar (like this blog entry: https://www.graylog.org/blog/74-back-to-basics-from-single-server-to-graylog-cluster or these slides: https://www.slideshare.net/Graylog/graylog-engineering-design-your-architecture).  

If mantainers are ok with this idea I will start working on it, and submit a PR with a first draft.

**Comment by joschi** [comment]
@martinbydefault Awesome, thanks for volunteering! 👍 

In general, all valid settings are listed and documented in the Graylog configuration file (https://github.com/Graylog2/graylog2-server/blob/2.3.1/misc/graylog.conf) but having a more detailed explanation in the Graylog documentation doesn't hurt.

**Comment by jalogisch** [comment]
as with 3.x we will change some `server.conf` settings, this will be open until this new part created by @martinbydefault is ported to the new settings.

**Comment by danotorrey** [comment]
I believe this issue is now fully addressed in the latest Graylog documentation:

http://docs.graylog.org/en/2.5/pages/configuration/server.conf.html

Please let us know if you see any issues with this.
