### ISSUE TITLE
GELF spec needs a canonical address

### ISSUE THREAD

**Issue by mikkolehtisalo** [Graylog2/documentation#143]
For example, the link at logstash documentation broke recently:

https://www.elastic.co/guide/en/logstash/current/plugins-outputs-gelf.html

GELF spec perhaps needs a canonical address that will stay safe to link. The link to docs.graylog.org breaks easilyby time, too.

**Comment by joschi** [comment]
I wholeheartedly agree to this.

The current address of the GELF specification is http://docs.graylog.org/en/2.0/pages/gelf.html.

**Comment by joschi** [comment]
Google also reveals some dead links for the mentioned URL: [Google search](https://www.google.de/search?q="graylog2.org%2Fgelf%23specs")

**Comment by joschi** [comment]
FWIW, we've fixed the redirect for http://graylog2.org/gelf

**Comment by jalogisch** [comment]
as we have fixed the redirect we can't do anything more IMHO
