### ISSUE TITLE
Adding section about journald

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/documentation#147]
## Context

We need to add journald to the examples how to send logs into graylog
## Expected Content

we just need to verify if [this](https://graylogadmin.wordpress.com/journald-to-graylog/) is working and just add somewhere [here](http://docs.graylog.org/en/2.0/pages/sending_data.html#json-path-from-http-api-input)

**Comment by joschi** [comment]
We have the syslog stuff in a separate "Guide" repositories (which I personally do not like for such an integral part, but okay…):
- https://github.com/Graylog2/graylog-guide-syslog-linux
- https://github.com/Graylog2/graylog-guide-syslog-amqp

Does it make sense to put the systemd stuff also in separate repos?

**Comment by jalogisch** [comment]
it would - make sense.

**Comment by joschi** [comment]
Refs Graylog2/graylog2-server#2228

**Comment by jalogisch** [comment]
Refs https://github.com/mheese/journalbeat
