### ISSUE TITLE
Invalid link to 'RestPermissions.java' on System users page

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/documentation#155]
## Context

The "System users" page (`documentation/pages/users_and_roles/system_users.rst`) has an invalid link ( https://github.com/Graylog2/graylog2-server/blob/master/graylog2-shared/src/main/java/org/graylog2/shared/security/RestPermissions.java ) to "RestPermissions.java" (tested against 2.0.3 and master).
## Expected Content

The "RestPermissions.java" link should be to https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java .

**Comment by joschi** [comment]
@coffee-squirrel Thanks!
