### ISSUE TITLE
Link to documentation on nodes page is not opening in new window

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/documentation#16]
http://docs.graylog.org/en/latest/pages/architecture.html#highly-available-setup-with-graylog-radio

![bildschirmfoto 2015-05-21 um 17 19 08](https://cloud.githubusercontent.com/assets/6331205/7752067/c724c6b6-ffdd-11e4-8adc-6103982f8290.png)

**Comment by edmundoa** [comment]
This was fixed in 1.2.
