### ISSUE TITLE
graylog collector documentation::linux

### ISSUE THREAD

**Issue by realrobmorris** [Graylog2/documentation#160]
In the graylog documentation, at the link below, there is no information as to installation of any RPM based packages, only deb. However, if the link is followed to the actual release page, then RPM is available. 

Also, on the same page, at the beginning of the installation section, since there is a specific section on Windows, there should be some specification as to Linux as well. 

Page: 
http://docs.graylog.org/en/2.0/pages/collector_sidecar.html#linux-unix
## Expected Content

Need to put in instructions on installing via RPM. Also, is this collector sidecar available in the yum repo? Why or why not? Either way this needs to be documented. 

Documentation needs to be done so that people who have absolutely no experience with graylog can actually use it without using Google to figure out how to install/configure/etc. 
## Your Environment

Irrelevant, documentation missing/lacking.

**Comment by mariussturm** [comment]
I think all of your points are covered on the (unreleased) version of the same page: http://docs.graylog.org/en/2.1/pages/collector_sidecar.html#linux-unix
We switch the version after releasing Graylog 2.1

**Comment by realrobmorris** [comment]
Ok cool. Thanks!
