### ISSUE TITLE
Wrong Kafka documentation link

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/documentation#17]
When going to system/nodes/available input types in Graylog there is a Kafka documentation link linking to the input overview http://docs.graylog.org/en/1.0/pages/sending_data.html#json-path-from-http-api-input

I can not find any documentation on Kafka inputs at all. This either needs to be written or the link should be removed.

**Comment by jalogisch** [comment]
as this link is not available in v. 2.0.X this is not needed anymore
