### ISSUE TITLE
Websockets and proxy

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/documentation#18]
When using some proxy in front of Graylog, some configuration might be necessary in order to make the websockets loading metrics to work. By default they use the `/a/metrics` route. We need to add documentation for this.

**Comment by kroepke** [comment]
It is because of the route or the proxy?
IOW, sockjs should fall back to polling if the proxy doesn't support websockets.
If it uses /a/metrics directly, we should use the js router support for that.

**Comment by kroepke** [comment]
Some pointers for common http proxy servers:
 - http://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html
 - http://nginx.com/blog/websocket-nginx/

**Comment by jalogisch** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
