### ISSUE TITLE
Document new Kafka inputs in Graylog 1.1.x

### ISSUE THREAD

**Issue by joschi** [Graylog2/documentation#19]
There are several new Kafka-based inputs in Graylog 1.1.x which need to be documented.

Refs Graylog2/graylog2-server#322 and Graylog2/graylog2-server#1165

**Comment by jalogisch** [comment]
this is already merged - but this case not closed, so i'll close now

**Comment by joschi** [comment]
@jalogisch We're still missing documentation for our Kafka inputs.
