### ISSUE TITLE
Simple User Login Problem?

### ISSUE THREAD

**Issue by rsblack** [Graylog2/documentation#191]
Have a custom build;
Ubuntu 16.
GL 2.1.x
ELS 2.x 
Mongo 2.6.x

Web console is up but cannot for the life of me get logged in, initially; where about are the parameters in the server.conf to modify such? 
Is the user and password for the web-console defined by secret?
## Out of Context

PEBCAK?

Much Obliged!
-Riley

**Comment by joschi** [comment]
@rsblack We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
