### ISSUE TITLE
Documentation for Graylog Side Car collector  for filebeat utility is incomplete 

### ISSUE THREAD

**Issue by kunalpatil3017** [Graylog2/documentation#201]
## Your Environment

- Graylog Version:
- Elasticsearch Version:
- MongoDB Version:
- Operating System:
- Browser version:

**Comment by joschi** [comment]
@kunalpatil3017 Seriously, you need to provide some details. Otherwise nobody besides yourself knows what you mean…

**Comment by kunalpatil3017** [comment]
Sorry for that
Please guide me in details
How to implement beat collector on remote host collect logs which is in
multiple line format

**Comment by jalogisch** [comment]
Dear @kunalpatil3017 

This place is for issues with the documentation, you are asking for advice how to implement something. This is not the correct location for this!

The right location for this would be our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

If you need more assistance please feel free to get in contact with the [professional support](https://www.graylog.org/professional-support) 

Thank you!

**Comment by mariussturm** [comment]
@kunalpatil3017 please read about multiline support in Filebeat directly in there documentation: https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html#multiline We dont want to copy all the documentation for every collector into our own. We write only about the Sidecar specific parts.
