### ISSUE TITLE
Remove logstash/fluentd from collector-sidecar page

### ISSUE THREAD

**Issue by omercnet** [Graylog2/documentation#221]
The page https://github.com/Graylog2/documentation/blob/2.1/pages/collector_sidecar.rst includes this image https://github.com/Graylog2/documentation/blob/2.1/images/sidecar_overview.png which shows graylog sidecar manages/configures logstash/fluentd when in fact it only supports file/winlogbeats and nxlog

**Comment by jalogisch** [comment]
@omercnet we will take care of this and create new images. The used Image was created during the planning and not updated after the first release.
