### ISSUE TITLE
Document all graylog-ctl parameters

### ISSUE THREAD

**Issue by joschi** [Graylog2/documentation#222]
The documentation of the graylog-ctl script is missing some important parameters such as index rotation and retention settings.

**Comment by jalogisch** [comment]
I guess that describe all settings that can be set in the graylog-settings.json is what you like to have? 

(means this: https://github.com/Graylog2/omnibus-graylog2/blob/2.1/files/graylog-cookbooks/graylog/attributes/default.rb )

**Comment by joschi** [comment]
@jalogisch There are a few commands for `graylog-ctl` which aren't documented at all. Documenting these would be a good start.

https://github.com/Graylog2/omnibus-graylog2/tree/2.1/files/graylog-ctl-commands

**Comment by jalogisch** [comment]
@mariussturm had done this for 2.2 https://github.com/Graylog2/documentation/commit/e72ae502b3d47360cacb4248a7975cc42e3256e8

**Comment by mariussturm** [comment]
Closing this cause 2.2 is around the corner.
