### ISSUE TITLE
Email alert Graylog 2.1 error !!!

### ISSUE THREAD

**Issue by manhdinh** [Graylog2/documentation#238]
Hello, i am using Graylog 2.1 and i can't send email alert ( even test mail ). 
Firstly, i configure postfix mail to send a test email, everything seem to be allright. Here is my main.cfg : 
http://paste.openstack.org/show/593977/ .
I send a test email using echo command : echo "This is a test." | mail -s "test message" myemail. My email receive this test email. 
However when i configure email in the server.conf, i send a test email in the Graylog web-interface, the result in my graylog server log file is : 
http://paste.openstack.org/show/593978/ 
Here is my server.conf : 
http://paste.openstack.org/show/593980/

It seem to be that graylog can't convert to TLS socket, but i don't know why? 
And anyone can explain about the way Graylog send email alert ( through postfix email or otherway?...) 
A lot of thanks !!!

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
@manhdinh We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
