### ISSUE TITLE
Configuring Elasticsearch with docker install

### ISSUE THREAD

**Issue by javadan** [Graylog2/documentation#27]
Hi, 

The only mention of configuring ES in the docker page is that one can pass in an ES_MEMORY field
http://docs.graylog.org/en/1.1/pages/installation/docker.html

I've started a docker Graylog2, and am getting the 'Elasticsearch nodes with too low open file limit' message.  I can see there is a page for configuring ES:
http://docs.graylog.org/en/1.1/pages/configuring_es.html

But I'm not sure where elasticsearch.yml or graylog.conf is stored.  Docker seems to be a black box.  But maybe I'm misunderstanding docker.  Must I 'go into' the container somehow, to find these files?  

Is the docker install a viable production option?  "We strongly recommend to use a dedicated Elasticsearch cluster for your Graylog setup." - (I'm using the one that comes with the docker file, so I presume I'm ok?).

Regards
Daniel

**Comment by jalogisch** [comment]
Hej Dani
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
