### ISSUE TITLE
The graylog blog problems

### ISSUE THREAD

**Issue by CrazyLlama** [Graylog2/documentation#276]
Hi, I'm just raising this issue as I believe it would be pertinent to rename "The Graylog Blog" as "The Grayblog"

## Context
While visiting https://www.graylog.org/blog I noticed that the designated name for this is "The Graylog Blog", I also noted that it wasn't called "The GrayBlog", a zingy-er and more punchy name that can make or break such an informative blog. Changing to this obviously better name has the potential to bring in _millions_ more people to this blog as well as making _a lot_ more money as they'll be more inclined to purchase commercial packages from yourselves because they'll see just how _damn cool_ you guys are.
 
## Expected Content
"The Graylog Blog" < "The GrayBlog"

## Your Environment
Google Chrome Version 55.0.2883.87

**Comment by CrazyLlama** [comment]
See attached image: http://i.imgur.com/5EThNpY.png

**Comment by jalogisch** [comment]
nice idea @CrazyLlama - we discussed this internal but will not make this change.

But, we would like to send you some swag. Please provide us your address!
