### ISSUE TITLE
No documentation for plugin development (except AlarmCallback)

### ISSUE THREAD

**Issue by dfch** [Graylog2/documentation#3]
Now that you have released v1 of your product (congrats for that btw) I would really appreciate some official documentation for writing plugins. I have by now somehow managed to create all *standard* plugin types, but really would like to know the official way on this ought to be done.
One of my customers really complains that it is currently still very hard to start from scratch - especially for input (yes, there are examples by now) and rest resource (where I could not find an example) it was quite hard to find out.
In addition it would be beneficial to get more information about the built-in transports and codecs.
Or I can offer to write down something (already have some parts) if you tell me what you expect.
Documentation is key to get a community adding plugins so you can better compete with other products like splunk and logstash.
Otherwise just keep up the good work! Looking forward to seeing Graylog evolve! Ronald

**Comment by jalogisch** [comment]
we have now http://docs.graylog.org/en/2.0/pages/plugins.html @dfch i think that should help!

**Comment by dfch** [comment]
@jalogisch thx - looks very good!
