### ISSUE TITLE
Graylog2 contribution documentation missed

### ISSUE THREAD

**Issue by stephen412** [Graylog2/documentation#304]
Graylog2 contribution documentation missed

## Context
      Can I get the Graylog2 contribution documents?
      I'm just going to do some contributions for this community but was stopped in few project compile or debug steps.
      It will much more efficient for my current items.
      My email address is: stephen.pu6@gmail.com

Thanks
Stephen
## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
@stephen412 Please see https://www.graylog.org/get-involved for various possibilities of contributing to Graylog. Thanks!

**Comment by stephen412** [comment]
Thanks Joschi.

So far, the problem is that I  was blocked on set up code build environment. 
Where can I find this kind of environment set up guilds?

Thanks
Stephen
