### ISSUE TITLE
Using open source graph/diagramming tool ?

### ISSUE THREAD

**Issue by tjyang** [Graylog2/documentation#31]
Hi 

I like to understand if this project will accept pull request for graylog related  diagrams draw by tool like Inkscape,Dia ...

**Comment by jalogisch** [comment]
@tjyang yes it will - if you are still interested!

**Comment by tjyang** [comment]
Thanks @jalogisch, understanding your position on diagramming tool. I will spend some time to draw a few diagrams regarding to  graylog2 project, using Dia. Hopefully there are enough graylog users know Dia tooll also. It won't be quick since my graylog project is currently not in high priority.

**Comment by tjyang** [comment]
Please review https://github.com/Graylog2/documentation/pull/102

**Comment by jalogisch** [comment]
Hej @tjyang lets discuss in the #102 now - will close this.
