### ISSUE TITLE
Default File locations for Ubuntu are incorrect 

### ISSUE THREAD

**Issue by msteelepmp** [Graylog2/documentation#311]
## Context

I am running the Graylog AWS AMI 2.2.2, upgraded to 2.2.3.  I wanted to increase the JVM Heap size for the graylog-server. But none of the JVM configuration files are in /etc/default . The best I can tell, the JVM heap is set in /opt/graylog/service/graylog-server/run. In tracking the code that launches graylog, I can't see that anything intervenes upstream in setting GRAYLOG_SERVER_JAVA_OPTS before the 'run' script.

## Expected Content

Change JVM reference from /etc/default to /opt/graylog/service (if that is in fact where it's suppose to be).

## Your Environment

* Graylog Version: 2.2.3
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Ubuntu 14.04

**Comment by jalogisch** [comment]
@msteelepmp if you are running AWS you need to look at the [Omnibus](http://docs.graylog.org/en/2.2/pages/configuration/file_location.html#omnibus-package) location and not the Ubuntu location.

> This paragraph covers Graylog installations via OVA, on AWS (via AMI), and on OpenStack using the Graylog Omnibus package.

**Comment by msteelepmp** [comment]
Thanks, I found the file as stated in the document (once I scrolled down :). Also thanks for including a link to the customization of the JSON file.  Although more complete JSON options in the docs would be appreciated, at least I saw the memory part I needed. One additional question. Typically JVM is customized via JAVA_OPTS="-Xms1500m -Xmx2100m" whereas the memory allocation specified in /etc/graylog/graylog-settings.json are just 'memory', so is this equivalent to Xmx (i.e. max memory)?

`"custom_attributes": {
     "graylog-server": {
       "memory": "1700m"
     },
     "elasticsearch": {
       "memory": "2200m"
     }
  }`

**Comment by joschi** [comment]
@msteelepmp The JVM settings will be `-Xms1g -Xmx<graylog-sever.memory>`, see https://github.com/Graylog2/omnibus-graylog2/blob/2.2.3-2/files/graylog-cookbooks/graylog/templates/default/sv-graylog-server-run.erb#L11

If you have more questions, please post them to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
