### ISSUE TITLE
Package inputenc Error: Unicode char \u8:✔ not set up for use with LaTeX.

### ISSUE THREAD

**Issue by tjyang** [Graylog2/documentation#32]
I am logging this issue from "make latexpdf".  This is on Fedora 22 OS with texlive packages all installed.

<pre>
Chapter 5.
[43] <collector_win_install_1.png, id=1179, 793.96625pt x 807.015pt>
<use collector_win_install_1.png> <use collector_win_install_1.png> [44]
Underfull \hbox (badness 10000) in paragraph at lines 2376--2377
[]\T1/ptm/m/n/10 Change into the ex-tracted col-lec-tor di-rec-tory and cre-ate
 a col-lec-tor con-fig-u-ra-tion file in
<collector_win_install_2.png, id=1192, 902.37125pt x 437.635pt>
<use collector_win_install_2.png> <use collector_win_install_2.png> [45 <./coll
ector_win_install_1.png>] [46 <./collector_win_install_2.png>]
<collector_win_install_3.png, id=1201, 1330.9725pt x 701.62125pt>
<use collector_win_install_3.png> <use collector_win_install_3.png>
Underfull \hbox (badness 10000) in paragraph at lines 2432--2433
[]\T1/ptm/m/n/10 If you choose the op-er-at-ing sys-tem in-stal-la-tion method,
 the con-fig-u-ra-tion file de-faults to
[47 <./collector_win_install_3.png>]
Underfull \hbox (badness 10000) in paragraph at lines 2506--2507
[]\T1/ptm/m/n/10 Please make sure to es-cape the \T1/pcr/m/n/10 \ \T1/ptm/m/n/1
0 char-ac-ter in Win-dows paths: \T1/pcr/m/n/10 path = "C:\\Program

Underfull \hbox (badness 10000) in paragraph at lines 2513--2514
[]\T1/ptm/m/n/10 Please make sure to es-cape the \T1/pcr/m/n/10 \ \T1/ptm/m/n/1
0 char-ac-ter in Win-dows paths: \T1/pcr/m/n/10 path = "C:\\Program
[48]
Overfull \hbox (29.49223pt too wide) in paragraph at lines 2554--2555
[]\T1/ptm/m/n/10 A usual glob/wildcard string you know from other tools might b
e \T1/pcr/m/n/10 /var/log/apache2/**/*.{access,error}.log\T1/ptm/m/n/10 .

Underfull \hbox (badness 10000) in paragraph at lines 2554--2555
\T1/ptm/m/n/10 This means you are in-ter-ested in all log files which names end
 with \T1/pcr/m/n/10 .access.log \T1/ptm/m/n/10 or

Underfull \hbox (badness 10000) in paragraph at lines 2554--2555
\T1/pcr/m/n/10 .error.log \T1/ptm/m/n/10 and which are in a sub di-rec-tory of
\T1/pcr/m/n/10 /var/log/apache2\T1/ptm/m/n/10 . Ex-am-ple:
[49] [50] [51] [52]

! Package inputenc Error: Unicode char \u8:✔ not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.2877 \hline\end{tabulary}

?
</pre>

Reference: http://tex.stackexchange.com/questions/83440/inputenc-error-unicode-char-u8-not-set-up-for-use-with-latex

**Comment by joschi** [comment]
@tjyang Please upgrade your Sphinx installation to Sphinx 1.4.1. This problem should've been fixed in sphinx-doc/sphinx#1971.
