### ISSUE TITLE
"no security"

### ISSUE THREAD

**Issue by gaganova** [Graylog2/documentation#323]
I found this in the docs to be extremely irritating:
```
Warning
This setup should not be done on publicly exposed servers. This guide does not cover security settings!
```

Of course I am expecting the creators of a product to deliver an installation procedure that does not leave a system vulnerable - even MS tries to do that nowadays. 

Is that a documentation glitch? Or are you really saying "your systems will be vulnerable when you install this software"? 

Seems like something is very wrong here.

**Comment by joschi** [comment]
@gaganova The step-by-step guides cover a **basic** working Graylog setup.

Depending on your environment, security settings are more or less complex and would unnecessarily complicate these **basic** guides.

Security settings are covered in other parts of the documentation.
