### ISSUE TITLE
Filebeat with Graylog2 for IIS logs

### ISSUE THREAD

**Issue by dsiconnelli** [Graylog2/documentation#373]
From a Windows 10 pro machine running Graylog 2.3.1 in virtual box I want to send IIS logs into Graylog.

I can't find an example of the Path to Logfile for the Filebeat input and I think that is what is wrong.  Here is what I got:
['C:\inetpub\logs\LogFiles\*\*']

The IIS logs I want are on the same Windows 10 pro.

* Graylog Version: 2.3.1-3 (in virtual box)
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Windows 10 pro
* Browser version: Internet Explorer 11

**Comment by mariussturm** [comment]
You created this issue in the `documentation` repository. Is this more a general question that could be answered in the Graylog commuity forum or do you mean this as a feedback to the current documentation?

**Comment by dsiconnelli** [comment]
Oh!  Maybe you're right.  I sould've posted there.  However, maybe it's related to documentation too since I can't find an example to collect IIS logs.

**Comment by joschi** [comment]
https://community.graylog.org/t/graylog-search-problem/2771

**Comment by joschi** [comment]
@dsiconnelli Collecting IIS logs is not different from collecting logs of any other application.

We certainly won't add instructions to the documentation for monitoring all applications you can think of. 😉

**Comment by dsiconnelli** [comment]
Thanks.
