### ISSUE TITLE
Installed plugins description field all referred to https://www.graylog.org/

### ISSUE THREAD

**Issue by tjyang** [Graylog2/documentation#377]
I was hoping to link back to graylog  doc section to explain the plugin in detail on what/how to use.
## Context

![image](https://user-images.githubusercontent.com/378638/31643490-6f96eb84-b2b6-11e7-865c-867806d9e5fb.png)

## Your Environment

* Graylog Version: 2.3.1
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
@tjyang There aren't detailed instructions for every plugin, so the link to the Graylog website is fine for these without detailed docs.

For the others, I've created PRs to link to the respective documentation.

**Comment by bernd** [comment]
The PRs have been merged.
