### ISSUE TITLE
Generated online documentation bug: Link to Edit on Github is incorrect

### ISSUE THREAD

**Issue by bronius** [Graylog2/documentation#389]
The generated Read the Docs online Graylog documentation link to Edit on Github link is incorrect and results in a Github 404.

## Context
Visit any generated Graylog online documentation page, and click the Edit on Github link.

Ex:
1. Visit Pipelines page in documentation http://docs.graylog.org/en/2.3/pages/pipelines/pipelines.html in a web browser
2. See Pipelines documentation.
3. Click Edit on Github.
3. See that you arrive at a Github 404 page:  https://github.com/Graylog2/documentation/blob/origin/2.3/pages/pipelines/pipelines.rst

## Expected Content
Link should instead point to https://github.com/Graylog2/documentation/blob/2.3/pages/pipelines/pipelines.rst
(no "origin" in the path)
This is known to affect at least all Graylog versions 2.x and 3.x documentation.

**Comment by joschi** [comment]
This seems to be a bug at ReadTheDocs.org:

* rtfd/readthedocs.org#1820
* rtfd/readthedocs.org#1637

**Comment by joschi** [comment]
This has been fixed in ReadTheDocs.org.
