### ISSUE TITLE
Images in the docs don't match the text

### ISSUE THREAD

**Issue by 211217613** [Graylog2/documentation#405]
## Context

The screen shots don't match the directions in the documentation. I understand this might be small issue but can be confusing for people with less experience. 
Pertains to the section in getting started when modifying `/etc/rsyslog.conf` 
## Expected Content

Accurate screenshots

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
> The screen shots don't match the directions in the documentation.

Which pages are you referring to specifically?

**Comment by 211217613** [comment]
The second screenshot on this [page]( http://docs.graylog.org/en/2.4/pages/getting_started/rsyslog.html?highlight=rsyslog) doesn't match the directions right above it. 

> `*.* @127.0.0.1:514;RSYSLOG_SyslogProtocol23Format `

There are other inconsistencies in other screenshots I think, I just can't find them.

**Comment by joschi** [comment]
@211217613 Thanks for the hint! We'll remove the inconsistent screenshot from the Getting Started Guide.

Feel free to open a new issue if you find another inconsistency.
