### ISSUE TITLE
"short_message" is stored as "message" and "host" is stored as "source"

### ISSUE THREAD

**Issue by roflrox** [Graylog2/documentation#413]
When sending GELF-Input Data the field "short_message" is stored as "message" and the field "host" is stored as "source". This isn't documented.

As implemented in GelfCodec.java:

```
final Message message = new Message(
   stringValue(node, "short_message"),
   stringValue(node, "host"),
   timestamp
 );
```

and Message.java:

```
 public Message(final String message, final String source, final DateTime timestamp) {
        fields.put(FIELD_ID, new UUID().toString());
        addRequiredField(FIELD_MESSAGE, message);
        addRequiredField(FIELD_SOURCE, source);
        addRequiredField(FIELD_TIMESTAMP, timestamp);
}
```

## Expected Content
A hint in the GELF Payload Specification,

**Comment by joschi** [comment]
@roflrox You're mixing up the internal representation of a message in Graylog (i. e. [`Message`](https://github.com/Graylog2/graylog2-server/blob/2.4.3/graylog2-server/src/main/java/org/graylog2/plugin/Message.java)) and the GELF transport (i. e. [`GelfCodec`](https://github.com/Graylog2/graylog2-server/blob/2.4.3/graylog2-server/src/main/java/org/graylog2/inputs/codecs/GelfCodec.java)) and payload format (i. e. [`GELFMessage`](https://github.com/Graylog2/graylog2-server/blob/2.4.3/graylog2-server/src/main/java/org/graylog2/inputs/codecs/gelf/GELFMessage.java)) as specified by the [GELF specification](http://docs.graylog.org/en/2.4/pages/gelf.html).
