### ISSUE TITLE
Download location of Graylog Enterprise tar-balls

### ISSUE THREAD

**Issue by joschi** [Graylog2/documentation#419]
The documentation (http://docs.graylog.org/en/2.4/pages/enterprise/setup.html#tarball) says:
> If you have done a manual installation or want to include only parts of the enterprise plugins you can get the tarball from the [Graylog Enterprise web page](https://www.graylog.org/enterprise/).

Unfortunately there is no download link for the Graylog Enterprise tar-ball on that page or the whole website for that matter.

The download link is (as of 2018-02-21) only provided in the email users receive after requesting a free Graylog Enterprise license.

**Comment by jalogisch** [comment]
We have that tarball download now in the docs, so this issue is moved over to the website repo with the question if we want that only this way or add it to the website.
