### ISSUE TITLE
Add FAQ entry for how to handle/fix unassigned shards in ES

### ISSUE THREAD

**Issue by joschi** [Graylog2/documentation#42]
https://t37.net/how-to-fix-your-elasticsearch-cluster-stuck-in-initializing-shards-mode.html

**Comment by SamParikh** [comment]
Hi Jochen,

I had one of these this morning, how timely!  Tell me, would you just want
to link to this article or should we somehow re-write it?  I think its
pretty good as is, but would like your opinion.

Thanks,
-Sam

On Thu, Dec 10, 2015 at 3:30 AM, Jochen Schalanda <notifications@github.com>
wrote:

>
> https://t37.net/how-to-fix-your-elasticsearch-cluster-stuck-in-initializing-shards-mode.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Graylog2/documentation/issues/42>.
>



-- 
Sam Parikh
Graylog <http://www.graylog.org>
*(+1) 832-541-7364*

**Comment by joschi** [comment]
@SamParikh It's quite a common problem if people don't monitor the disk usage of their Elasticsearch nodes and they ran out of disk space (or reached the high disk watermark). In the end we can simply link the blog post now but should probably write a version of it tailored towards the use of ES in Graylog eventually.

**Comment by jalogisch** [comment]
latest versions of elasticsearch has the high/low watermark and the latest version of Graylog can handle that. 

it is very unlikely that we have someone running into this. If that was done on purpose.
