### ISSUE TITLE
Remove references to the removed drools and blacklist features

### ISSUE THREAD

**Issue by bernd** [Graylog2/documentation#438]
The drools plugin has been moved into a plugin and the blacklist filter feature, which was based on drools, got removed for 3.0. We need to adjust the documentation accordingly.

- Drools removal: https://github.com/Graylog2/graylog2-server/pull/4694
- Blacklist removal: https://github.com/Graylog2/graylog2-server/pull/4698

**Comment by jalogisch** [comment]
fixed by the PR
