### ISSUE TITLE
"documentation/pages/getting_started/stream_alerts.rst"  issue...?

### ISSUE THREAD

**Issue by lharles** [Graylog2/documentation#44]
The section of the document titled "Create a Stream Rule" reads as:
"Pick the Syslog UDP Input, and click Add stream rule."
[Image for picking the item & add stream rule button.]

Followed by:
"Then, type in the values shown below and hit save.

Then click I’m done!

We have just configured this stream to process in real time all the messages that come in from the security/authorization facility.

Now let’s create the alert."

The issue is that, at the line stating, "Then, type in the values show below and hit save", there is no image or values given.

I'm very much a novice & new to Graylog, but I tried several times to glean the information from text & sections following & didn't find that information to create the initial/test stream rule, in that location...

**Comment by Houtek** [comment]
Came here to look for the missing statements and found this issue. I have the same problem. New to Graylog and stuck in this part of the documentation.

**Comment by jalogisch** [comment]
image is present and shown - did you still have the Problem?

**Comment by jalogisch** [comment]
will close now as of now response
