### ISSUE TITLE
Debian Stretch install uses Jessie source list for mongodb

### ISSUE THREAD

**Issue by 20k-ultra** [Graylog2/documentation#445]
## Context
When following the [docs](http://docs.graylog.org/en/2.4/pages/installation/os/debian.html#debian-installation) which states the install is for Debian 9 the MongoDB install instructions say to add the jessie/mongodb-org/3.6 to the source list. This will cause cause the install to not be successful due to dependencies.

After switching to stretch/mongdb-org/3.6 the install was successful. Perhaps edit the documentation to add some clarification.

## Expected Content
MongoDB 3.6 install on Debian 9

* Graylog Version: 2.4
* Elasticsearch Version:
* MongoDB Version: 3.6
* Operating System: Debian 9
* Browser version:

**Comment by joschi** [comment]
@20k-ultra Good catch. Thanks!
