### ISSUE TITLE
Collector Sidecar first start clarification

### ISSUE THREAD

**Issue by 20k-ultra** [Graylog2/documentation#446]
As of Debian 9 it uses systemd so I suggest updating the docs [here](http://docs.graylog.org/en/2.4/pages/collector_sidecar.html#first-start) so that Debian is with RedHat/CentOS on how to start the service. I think this is appropriate since Debian 9 is the latest version.

* Graylog Version: 2.4
* Operating System: Debian 9

**Comment by joschi** [comment]
@20k-ultra Would you like to contribute a pull request to the documentation changing this aspect?

It would be great to still have some explanation for Upstart/SysV init, too.

**Comment by 20k-ultra** [comment]
sure I'll give it a try!
