### ISSUE TITLE
Setup HTTPS for docs site

### ISSUE THREAD

**Issue by 20k-ultra** [Graylog2/documentation#454]
graylog.org is being served over HTTPS and would like to just give me opinion that I'd like the docs to run on HTTPS too.

sorry this isn't the type of bug I can try and fix myself :(

**Comment by joschi** [comment]
@20k-ultra ReadTheDocs.org currently doesn't support HTTPS for custom domains.

Once rtfd/readthedocs.org#2652 has been implemented, we can and will activate HTTPS for the Graylog documentation.

**Comment by 20k-ultra** [comment]
ah ok my apologies.
