### ISSUE TITLE
Documentation: Move or Remove or Annotate Elasticsearch Upgrade mention

### ISSUE THREAD

**Issue by bronius** [Graylog2/documentation#463]
In the Upgrade documentation for Graylog, a big giant mention of Elasticsearch 2.x -> 5.x is made, but there's no hint as to who when or why it should be done.

## Context
http://docs.graylog.org/en/2.4/pages/upgrade.html#upgrading-elasticsearch
https://github.com/Graylog2/documentation/blob/2.4/pages/upgrade.rst#upgrading-elasticsearch

## Expected Content
I think Elasticsearch 2.x -> 5.x should be moved to its entirely own page under somewhere Upgrading or alongside it so that someone like me doesn't get confused by it appearing as "part of Upgrading Graylog."  Hmm.. Or title on that broad heading could change to "Upgrading Graylog and Elasticsearch."

According to the docs, Graylog 2.x introduced Elasticsearch 2.x, but I don't see where/when 5.x came about.  I think I am on ES 5.x already (since Graylog 2.3, my original install from package).

* Mention should be made of where a Graylog sysadmin can find his current version of Elasticsearch.
* If ES 2.x -> 5.x doesn't need to happen, it should be shown marked Optional and what benefits it might provide.
* If 5.x is a requirement of or ships with a particular minor version of Graylog 2.x (doesn't seem to be), it should be mentioned in the dedicated Graylog minor version page.

**Comment by jalogisch** [comment]
@bronius could you please check the linked PR if that would clarify what you miss in our documentation about the Elasticsearch update.

Waiting for your answer.
Jan

**Comment by bronius** [comment]
Super, thanks @jalogisch.  Makes sense to me!

One thing I'd add is the motivation behind upgrading Elasticsearch from 2.x to 5.x.  Is it speed?  More capabilities (that manifest in Graylog)?  Just good practice to use the latest so that one day you're not stuck on an unsupported ES?  If no direct benefits, maybe just mention "no difference in Graylog UX, just back end performance improvements indexing, see https://www.elastic.co/blog/elasticsearch-5-0-0-released" or something.

If that statement is generally correct ^^, I'll happily recraft that whole section just a little bit and make a new PR.

Thanks!
-Bronisu

**Comment by jalogisch** [comment]
Sorry @bronius I did not follow up sooner.

The reason for the upgrade can be that you want the new features in Graylog - that are only possible with the new ES5. In addition you need ES5 for 3.0 to work so as you do not like to have a complete downtime for the environment you will do the ES upgrade earlier. 

So the motivation is new features, future compatibility and not using a EOL product. 

If you feel you should change the section, I'm waiting for the PR. Until then I'll close this.
