### ISSUE TITLE
Elasticsearch sharding green state

### ISSUE THREAD

**Issue by and0x000** [Graylog2/documentation#504]
## Context

I am running a single instance of the Graylog stack on a server. This means, I only have one instance of Elasticsearch locally available. The section regarding Elasticsearch is completely default. The documentation states, that system/overview -> overview should display the Elasticsearch state as yellow, as there is only this one instance.

> With only one Elasticsearch node, the cluster state cannot become green because shard replicas cannot be assigned.
http://docs.graylog.org/en/2.4/pages/configuration/elasticsearch.html#cluster-status-explained

## Expected Content

I expected the Elasticsearch state to be yellow. However, it is displayed as green.

## Your Environment

* Graylog Version: 2.4.6+ceaa7e4
* Elasticsearch Version: 5.6.13
* MongoDB Version:  3.6.9
* Operating System: Debian 9.6 Stretch
* Browser version: Firefox 63.0

**Comment by danotorrey** [comment]
@jalogisch Do you have any thoughts on this?

**Comment by jalogisch** [comment]
actually, it depends on the sharding and replica settings you have. @and0x000 this comment is from the time where this part of the docs as part of the virtual appliance.

This is only true when you have some specific settings for your elasticsearch indices.

**Comment by and0x000** [comment]
Thank you for satisfying my curiosity on this (very) minor issue :)

Should you require more information from my side, please let me know.
