### ISSUE TITLE
pages / pipelines / rules.rst - cannot access fields containing "dots"

### ISSUE THREAD

**Issue by demospace** [Graylog2/documentation#523]
## Context

This statement isn't entirely accurate, and doesn't provide caveat information:

> Variables need to be defined before they can be used. Their fields (if any) can be accessed using the name.field notation in any place where a value of the field's type is required.

I went looking for information on how to access fields with "dots" in their name in pipeline rules and came up empty.

If a JSON input is used and a field named "id.orig_h" is added to a document before it's sent to elasticsearch, that field's value cannot be accessed in pipeline rules. None of the following seem to work:
$message.id.orig_h
$message[id.orig_h]
$message["id.orig_h"]

## Expected Content
Information on how to access these fields or a warning indicating they are inaccessible in pipeline rules.

## Your Environment

* Graylog Version: 2.4
* Elasticsearch Version: 5.6.3
* MongoDB Version: na
* Operating System: Ubuntu
* Browser version: na

**Comment by jalogisch** [comment]
if you ingest messages as JSON you actually need to make some kind of JSON parsing at all before you can access the fields. 

Graylog does not automatically parse JSON messages and make fields available.

```
let json_result = parse_json(to_string($message.message));
let json_fields = select_jsonpath(json_result,
{ pool_member_name: "$.pool_member_name",
address: "$.address",
port: "$.port",
});
set_fields(json_fields);
```
