### ISSUE TITLE
update OVA configuration / settings 

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/documentation#526]
## Context
as we have changed the OVA we need to adjust the documentation for 3.0 - remove not available parts (`graylog-ctl`?) and enable users of the OVA to find help for the tasks that are done prior with on the old image. 

## Your Environment
* Graylog Version: 3.0

**Comment by edmundoa** [comment]
I think this is done in #557, please reopen if something is missing.

**Comment by visal94** [comment]
Plz help ,, i was download OVA from Graylog website Then i import ova to vmware workstation , i can not login to web 
user : admin , password : admin  (or other user & password). i tried to changed password too but it display   E45: 'readyonly'option is set (add ! to override).   USER & PASSWORD i log to use ova file   "ubuntu"

NOTE: Graylog Version  3.2.0-6   
![123](https://user-images.githubusercontent.com/68242344/87335910-40597b00-c56b-11ea-8616-f7cc0a926ee3.PNG)


@edmundoa @jalogisch

**Comment by visal94** [comment]
and below for web interface
![1234](https://user-images.githubusercontent.com/68242344/87336504-2704fe80-c56c-11ea-878e-8439f4881bdf.PNG)

**Comment by mariussturm** [comment]
@visal94 'admin':'admin' is not the default password anymore for the OVA appliances. A random password is generated and displayed on the console the first time the machine spins up.

**Comment by visal94** [comment]
@mariussturm  i'm really thanks for your answer, i have done on the issue !!!
