### ISSUE TITLE
Is the field verification regex correct?

### ISSUE THREAD

**Issue by togakangaroo** [Graylog2/documentation#53]
[In the docs](http://docs.graylog.org/en/latest/pages/gelf.html#gelf-format-specification)

> every field you send and prefix with a _ (underscore) will be treated as an additional field. Allowed characters in field names are any word character (letter, number, underscore), dashes and dots. The verifying regular expression is: ^[w.-]*$

This is not what that regular expression does. Or maybe I'm misunderstanding something? Did you mean `\w\.-`? Also this regex does not force the initial underscores

**Comment by joschi** [comment]
@togakangaroo Good catch! Thanks for reporting this. The correct regular expression hasn't been displayed due to erroneous markup on that page.
