### ISSUE TITLE
Server currently unavailable

### ISSUE THREAD

**Issue by markgraf** [Graylog2/documentation#538]
I just tried to install graylog following the steps detailed on:
http://docs.graylog.org/en/2.5/pages/installation/vagrant.html#installation

When loading the webinterface: I get "Server currently unavailable"

## Context

This is the detailed error message:
<pre>
This is the last response we received from the server:

Error message
Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
Original Request
GET http://127.0.0.1:8080/api/system/sessions
Status code
undefined
Full error message
Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
</pre>

As far as I can see, nothing is listening on port 8080.
So there might be something missing in the documentation for the installation in a vagrant-box.
Or maybe in the provided vagrant-box itself?

## Expected Content
A working web-interface.

## Your Environment

###graylog-ctl status
<pre>
run: elasticsearch: (pid 976) 1841s; run: log: (pid 975) 1841s
run: etcd: (pid 981) 1841s; run: log: (pid 980) 1841s
run: graylog-server: (pid 983) 1841s; run: log: (pid 982) 1841s
run: mongodb: (pid 972) 1841s; run: log: (pid 971) 1841s
run: nginx: (pid 987) 1841s; run: log: (pid 986) 1841s
</pre>

###netstat
<pre>
root@graylog:~# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:2380          0.0.0.0:*               LISTEN      981/etcd
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      622/rpcbind
tcp        0      0 10.0.2.15:9200          0.0.0.0:*               LISTEN      976/java
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      987/nginx.conf
tcp        0      0 10.0.2.15:9300          0.0.0.0:*               LISTEN      976/java
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1054/sshd
tcp        0      0 127.0.0.1:6010          0.0.0.0:*               LISTEN      2187/0
tcp        0      0 0.0.0.0:41308           0.0.0.0:*               LISTEN      661/rpc.statd
tcp        0      0 0.0.0.0:27017           0.0.0.0:*               LISTEN      972/mongod
tcp6       0      0 :::111                  :::*                    LISTEN      622/rpcbind
tcp6       0      0 :::22                   :::*                    LISTEN      1054/sshd
tcp6       0      0 ::1:6010                :::*                    LISTEN      2187/0
tcp6       0      0 :::4001                 :::*                    LISTEN      981/etcd
tcp6       0      0 :::34945                :::*                    LISTEN      661/rpc.statd
tcp6       0      0 :::9000                 :::*                    LISTEN      983/java
tcp6       0      0 :::2379                 :::*                    LISTEN      981/etcd
</pre>

* Graylog Version: 2.5.1-1
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Ubuntu 14.04.5 LTS
* Browser version: Vivaldi 2.2.1388.37, Firefox ESR 52.6.0, IE 11

**Comment by markgraf** [comment]
Web-Developer-Console in Vivaldi gave me additional info:

<pre>
127.0.0.1:8080/api/:1 Failed to load resource: the server responded with a status of 400 (Received invalid request from Client)
localhost/:1 Access to XMLHttpRequest at 'http://127.0.0.1:8080/api/' from origin 'http://localhost:10000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
Input.jsx:8 Input elements should have an id prop, generating one for you
d @ Input.jsx:8
2client.js:772 OPTIONS http://127.0.0.1:8080/api/ 400 (Received invalid request from Client)
l._end @ client.js:772
l.end @ client.js:676
(anonymous) @ index.js:80
a @ bluebird.js:992
o._resolveFromExecutor @ bluebird.js:3249
o @ bluebird.js:2845
i.promise @ index.js:79
i.then @ index.js:121
ping @ ServerAvailabilityStore.js:25
:10000/#:1 Access to XMLHttpRequest at 'http://127.0.0.1:8080/api/' from origin 'http://localhost:10000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
2client.js:772 OPTIONS http://127.0.0.1:8080/api/ 400 (Received invalid request from Client)
l._end @ client.js:772
l.end @ client.js:676
(anonymous) @ index.js:80
a @ bluebird.js:992
o._resolveFromExecutor @ bluebird.js:3249
o @ bluebird.js:2845
i.promise @ index.js:79
i.then @ index.js:121
ping @ ServerAvailabilityStore.js:25
:10000/#:1 Access to XMLHttpRequest at 'http://127.0.0.1:8080/api/' from origin 'http://localhost:10000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
2client.js:772 OPTIONS http://127.0.0.1:8080/api/ 400 (Received invalid request from Client)
l._end @ client.js:772
l.end @ client.js:676
(anonymous) @ index.js:80
a @ bluebird.js:992
o._resolveFromExecutor @ bluebird.js:3249
o @ bluebird.js:2845
i.promise @ index.js:79
i.then @ index.js:121
ping @ ServerAvailabilityStore.js:25
:10000/#:1 Access to XMLHttpRequest at 'http://127.0.0.1:8080/api/' from origin 'http://localhost:10000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
2client.js:772 OPTIONS http://127.0.0.1:8080/api/ 400 (Received invalid request from Client)
l._end @ client.js:772
l.end @ client.js:676
(anonymous) @ index.js:80
a @ bluebird.js:992
o._resolveFromExecutor @ bluebird.js:3249
o @ bluebird.js:2845
i.promise @ index.js:79
i.then @ index.js:121
ping @ ServerAvailabilityStore.js:25
:10000/#:1 Access to XMLHttpRequest at 'http://127.0.0.1:8080/api/' from origin 'http://localhost:10000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
2client.js:772 OPTIONS http://127.0.0.1:8080/api/ 400 (Received invalid request from Client)
l._end @ client.js:772
l.end @ client.js:676
(anonymous) @ index.js:80
a @ bluebird.js:992
o._resolveFromExecutor @ bluebird.js:3249
o @ bluebird.js:2845
i.promise @ index.js:79
i.then @ index.js:121
ping @ ServerAvailabilityStore.js:25
:10000/#:1 Access to XMLHttpRequest at 'http://127.0.0.1:8080/api/' from origin 'http://localhost:10000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
</pre>

**Comment by markgraf** [comment]
An Update:

I found these lines in /var/log/graylog/server/current:

<pre>
2019-01-24_11:40:56.30073 ERROR [LookupDataAdapter] Couldn't start data adapter abuse-ch-ransomware-ip/5c4884744fa6a31a13b84641/@c31a971>
2019-01-24_11:40:56.31826 ERROR [LookupDataAdapter] Couldn't start data adapter tor-exit-node/5c4884754fa6a31a13b8465f/@1019f29c>
</pre>

I guess a tor-exit node was not supposed to be part of the package?

**Comment by lennartkoopmann** [comment]
Hi! What you are seeing is our TOR Exit Node lookup table data adapter starting up. It's a piece of functionality that allows you to compare IP addresses against a list of known TOR exit nodes to, for example, look up if someone used TOR to log in to a service. The same applies to the [Abuse.ch Ransomware list](https://ransomwaretracker.abuse.ch/).

**Comment by markgraf** [comment]
*Phew* And there I was already sweating...
Good to know.

I can get back to wondering why I do not get this thing up and running then, starting with a fresh box  :-)
Sorry for panicking...

**Comment by markgraf** [comment]
OK, got it: I needed to do

<pre>
graylog-ctl set-external-ip http://192.168.56.56:9000/api
graylog-ctl reconfigure
</pre>

instead of the entry in the Vagrantfile:
<pre>graylog-ctl set-external-ip http://127.0.0.1:8080/api</pre>

"192.168.56.56" being the IP I configured in the Vagrantfile:
<pre> config.vm.network "private_network", ip: "192.168.56.56"</pre>
and "9000" being different to the "8080" shipped in the Vagrantfile. It wouldn't run with port 8080.

Up and running now.

Can you reproduce the issue? Or is that just my setup?

**Comment by mariussturm** [comment]
@markgraf this make sense if you use a private network. Thanks for the feedback, closing for now.
