### ISSUE TITLE
Does installation document over Ubuntu 14 is correct?

### ISSUE THREAD

**Issue by metalwood** [Graylog2/documentation#54]
http://docs.graylog.org/en/2.0/pages/installation/operating_system_packages.html

URL tells us the version is 2.0, but the download .deb link is 1.3, and I test it on Ubuntu 14.04 following those steps, installation fails.

**Comment by bernd** [comment]
Thanks for the report. The 2.0 documentation and the 2.0 release of Graylog is still work in progress.

I set the visibility of the 2.0 docs to hidden to avoid confusion.
