### ISSUE TITLE
Add documentation on how to setup TLS in Graylog

### ISSUE THREAD

**Issue by joschi** [Graylog2/documentation#56]
* https://www.playframework.com/documentation/2.3.x/ConfiguringHttps (old web interface)
* https://www.digitalocean.com/community/tutorials/java-keytool-essentials-working-with-java-keystores
* https://github.com/Graylog2/graylog2-server/blob/2.0.0-alpha.3/misc/graylog.conf#L57-L69
* https://github.com/Graylog2/graylog2-server/blob/2.0.0-alpha.3/misc/graylog.conf#L91-L103

**Comment by drewmmiranda** [comment]
The current documentation here is insufficient
http://docs.graylog.org/en/2.0/pages/installation/manual_setup.html

It is unclear specifically what should be done to produce a usable private key and x.509 cert. I've following any and all documentation I can find and nothing works with v2 of graylog.

**Comment by joschi** [comment]
@drewmmiranda What more than "To use proper certificates you must provide a PEM-encoded private key in PKCS#8 format and a X.509 certificate." do you need to know?

**Comment by drewmmiranda** [comment]
I followed that but it doesn't work. I specifically need to take my existing graylog web interface java keystore and extract the certs (which I have done) and convert them to the correct format. I have done this but graylog-server v2 does not consume the cert. See here: https://groups.google.com/forum/#!topic/graylog2/zxJZbiulvlY

**Comment by joschi** [comment]
This issue has been addressed in various commits (see references).

**Comment by drewmmiranda** [comment]
Thank you joschi, I owe you a beer. :)
