### ISSUE TITLE
Intent of "Message Backlog" for "Field Content Alert Condition" unclear

### ISSUE THREAD

**Issue by atc0005** [Graylog2/documentation#589]
## Context

The current description of the field:

> The number of messages to be included in alert notifications

It is unclear to me which of these meanings is correct:

- the number of messages that matched the specific condition 
- the number of messages that occur in the same time frame as the log pattern which matched the condition

I call myself reviewing the documentation, but I didn't spot the answer.

I'm happy to submit a PR which extends the explanation once I know which meaning is correct.

Thanks.

## Your Environment

* Graylog Version: 2.5.1

**Comment by atc0005** [comment]
![graylog_redmine_notification_condition_mailhandler_ignoring_email_2019-02-27](https://user-images.githubusercontent.com/36716992/53531053-b4e76300-3ab7-11e9-8fcc-26a35cf1a159.png)

Attaching screenshot to illustrate.

FWIW, it seems like the second meaning is correct based on the log messages included in the alert I received, but it is equally possible that the regex I attempted to apply (only match patterns that occur at the start of the line) is wrong and I'm getting more hits than intended.

**Comment by bernd** [comment]
@atc0005 

> the number of messages that matched the specific condition

This (your first point) is correct. The backlog contains messages that matched the specific condition. This is true for all built-in types of alert conditions.

The problem in your case is, that you used a regular expression as "Value". That doesn't work. We only support specific values in that field.

Do you still think that we need to update the documentation for the backlog setting?

**Comment by atc0005** [comment]
Hi @bernd,

Thanks for the follow-up.

> The problem in your case is, that you used a regular expression as "Value". That doesn't work. We only support specific values in that field.

I think I understand, but just to be clear: by specific values, do you mean literal values (no substitution, interpolation, regular expressions)?

If I want to apply regex style pattern matching as indicated by the screenshot, is that best done through the Search Query option on the "Create new Field Content Alert Condition" UI, or should the data be first parsed using extractors so that the Field Content Alert Condition is matching only against static values?

> Do you still think that we need to update the documentation for the backlog setting?

I think it would be helpful to spell it out to cover the bases so to speak. Because I wasn't sure how the Value field was being handled I couldn't be sure what I was seeing due to the backlog option. Some entries looked as desired, some looked coincidental, though that is explained now as (intentional?) lack of regex support for that field. 

I think it would be useful to clearly note that regexes are not supported for the Value field. Perhaps something like:

- **Web UI**: use something like "Literal value that the field should be checked against" (or similar language). If the reader knows that only literal values are supported and reads this first, then seeing the notes regarding the backlog matches will have more context
- **Documentation**: update http://docs.graylog.org/en/3.0/pages/streams/alerts.html#field-content-condition section to explicitly note that regular expressions are not supported and that field data should be broken out/parsed/whateverProperTerminologyIs first using an extractor (if that is the case) so that literal pattern/string matching works as expected against a whateverProperTerminologyIs field

**Comment by bernd** [comment]
> I think I understand, but just to be clear: by specific values, do you mean literal values (no substitution, interpolation, regular expressions)?

Exactly, only literal values are supported.

> If I want to apply regex style pattern matching as indicated by the screenshot, is that best done through the Search Query option on the "Create new Field Content Alert Condition" UI, or should the data be first parsed using extractors so that the Field Content Alert Condition is matching only against static values?

Yes, creating extractors or pipeline rules to extract data into fields first would simplify the usage of this alert condition.

Thanks for your input. We will update the documentation to clarify this.

**Comment by atc0005** [comment]
Thank you @bernd for taking the time to answer my questions. Thanks also for offering to update the docs to clarify the details, much appreciated!

**Comment by bernd** [comment]
This became obsolete with the new alerting system in Graylog 3.1. The new UI now supports search queries directly instead of exposing text fields that are converted to a search query in the backend. That means the regular search query documentation is applicable.
