### ISSUE TITLE
Graylog-ctl parameters incorrect

### ISSUE THREAD

**Issue by brandonegbert** [Graylog2/documentation#59]
http://docs.graylog.org/en/1.3/pages/installation/graylog_ctl.html#configuration-commands
```
sudo graylog-ctl set-email-config <smtp server> [–port=<smtp port> –user=<username> –password=<password> –no-tls –no-ssl]	
```
For at least the port and no-tls and no-ssl parameters they seem to require two dashes instead of one.

**Comment by mariussturm** [comment]
Thanks, fixed in `latest`!
