### ISSUE TITLE
replace() and regex_replace() are not documented

### ISSUE THREAD

**Issue by zoulja** [Graylog2/documentation#603]
https://www.graylog.org/post/announcing-graylog-v3-0-ga says "Various string functions: **replace, regex_replace**, starts_with, ends_with, join."
But search on http://docs.graylog.org/en/3.0/ doesn't show anything about these functions and how to use them.
It would be nice to get more info about it

**Comment by mehrenreich** [comment]
`regex_replace` and `replace` are fixed with this commit:

https://github.com/Graylog2/documentation/commit/b48b2d1d9e17102a0bce1f9deb6c160e423bb85e
