### ISSUE TITLE
Improve docker documentation by removing deprecated features

### ISSUE THREAD

**Issue by mbrucher** [Graylog2/documentation#613]
As the `--link` option is deprecated and doesn't work in a compose container, it would be great to get the example http://docs.graylog.org/en/3.0/pages/installation/docker.html fixed according to the docker best practices.

## Context

The documentation should be fixed to reflect the current state of docker best practices. Using a deprecated feature in the documentation gives the wrong message to new user as they may think that Graylog is not maintained anymore.

## Expected Content

Please remove the link usage and show how it can be replaced with something else (macros?).

## Your Environment

* Graylog Version: 3.0
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by loganmarchione** [comment]
@mbrucher - I also opened a similar issue on the [graylog-docker](https://github.com/Graylog2/graylog-docker) repo.
https://github.com/Graylog2/graylog-docker/issues/74

**Comment by jalogisch** [comment]
the above merged PR to the documentation fixed this.

**Comment by mbrucher** [comment]
Thanks a lot!!!
