### ISSUE TITLE
Loadbalancer state "THROTTLED" not documented

### ISSUE THREAD

**Issue by DerPhlipsi** [Graylog2/documentation#615]
## Context

I found this on my todo list, where it was added about 2 years ago. At the time I noticed, that the lbstatus endpoint has three possible values instead of the two documented ones, and the **THROTTLED** state has a good intention, since it can save a node from being overburdened, giving it a chance to recover and get fully operational again.

## Expected Content

The **THROTTLED** state should be documented, especially the boundaries of when it will be reported instead of **ALIVE** or **DEAD**.
We currently use it to mark the node as disabled in our loadbalancers, meaning this node can keep the currently active connections, but no new connections will be send here. I kinda got a grasp on this state by observing our cluster for a while, but an official documentation would be helpful.

Greets,
Phil

**Comment by Schuermi7** [comment]
Copy that.
Was searching myself to death for this.

**Comment by jalogisch** [comment]
The Response is `429 (too many request)`  when the Throttle level is reached:

https://github.com/Graylog2/graylog2-server/blob/master/misc/graylog.conf#L491-L493

This is the code for that.

https://github.com/Graylog2/graylog2-server/blob/09a70d08e113128b22322ee66be9c962407bfc0a/graylog2-server/src/main/java/org/graylog2/shared/rest/resources/system/LoadBalancerStatusResource.java#L66-L79

**Comment by Schuermi7** [comment]
I put in a pull request for a documentation change.
Thank you for your fast reply.
