### ISSUE TITLE
Timestamp whether from current timestamp by the server or client library

### ISSUE THREAD

**Issue by ts-kazuob** [Graylog2/documentation#639]
How can you tell whether timestamp is set to the current timestamp by the server or from the client library?

**Comment by jalogisch** [comment]
If you ask how you can see if Graylog has taken the timestamp from the message or if it has used the ingest time. That is currently not possible to tell.

We are using GitHub issues for tracking bugs in Graylog Documentation itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by ts-kazuob** [comment]
@jalogisch Thank you for your comment. I will post this one to discussion forum.
