### ISSUE TITLE
Add description how to acquire a session token from the Graylog REST API

### ISSUE THREAD

**Issue by joschi** [Graylog2/documentation#64]
https://gist.github.com/joschi/72fb7e75b171c10d3717

**Comment by jalogisch** [comment]
dublicate: https://github.com/Graylog2/documentation/issues/152

**Comment by joschi** [comment]
@jalogisch Session and access tokens are a different thing.

Session tokens expire after a certain time, while access tokens must explicitly be managed via the Graylog REST API.
