### ISSUE TITLE
Live Version of Documentation Rendering an 'en dash' instead of a 'double hyphen'

### ISSUE THREAD

**Issue by bensooter** [Graylog2/documentation#65]
On several pages of the live documentation on docs.graylog.org double hypens "--" in source blocks are being rendered as an en dash "–" instead which looks like just a single hyphen, and when copied and pasted into a terminal is copied over as a single hyphen.  The documentation source on Github correctly has double hyphens, rendering the documentation source with Sphinx correctly renders double hyphens, so not a problem with the source or config.  It appears this is a known bug, and the live site is likely using an outdated version of smartypants and just needs to update their sphinx install.

Some examples of en dashes instead of double hyphens from [http://docs.graylog.org/en/1.3/pages/installation/graylog_ctl.html](http://docs.graylog.org/en/1.3/pages/installation/graylog_ctl.html)  
 
Live Site:
`sudo graylog-ctl set-email-config <smtp server> [–port=<smtp port> –user=<username> –password=<password> –no-tls –no-ssl]`
Should Read:
`sudo graylog-ctl set-email-config <smtp server> [--port=<smtp port> --user=<username> --password=<password> --no-tls --no-ssl]`

Live Site:
```
sudo parted -a optimal – /dev/sdb unit \
compact mkpart primary ext3 “1” “-1”
```
Should Read:
```
sudo parted -a optimal -- /dev/sdb unit \
compact mkpart primary ext3 "1" "-1"
```

**Comment by mariussturm** [comment]
There are some issues around Sphinx and the way it shows dashes but the current version is the best I could get.
