### ISSUE TITLE
Graylog 3 External Authentication References Incompatible SSO Plugin

### ISSUE THREAD

**Issue by jandrusk** [Graylog2/documentation#650]
While reading the "External Authentication" section of the Graylog 3 documentation,  I noticed that reference was made to an SSO plugin that I attempted to use in our Graylog 3.X dev instance. It seems to be broken for 3.X per https://github.com/Graylog2/graylog-plugin-auth-sso/issues/37. 

I would expect that a plugin referenced in the 3.X documentation would be functional. 

Recommendation would be to remove the reference to the SSO plugin until it's compatible with Graylog 3.X.

**Comment by kroepke** [comment]
We'll have to rework the authentication layer for an upcoming version and should deprecate the SSO plugin as of now.

**Comment by fbettag** [comment]
That's just great, the oidc plugin is broken, the sso plugin is broken and will be removed.

**Comment by jalogisch** [comment]
as the given documentation link and plugin is still working I'll close this issue. 

Once we have reworked the authentication in Graylog this section needs rework to be done.

**Comment by harshit050499** [comment]
@jalogisch Any updates on this ?
i was implementing the same and got the same error.
