### ISSUE TITLE
Obsolete `script.disable_dynamic` elasticsearch configuration

### ISSUE THREAD

**Issue by xmik** [Graylog2/documentation#75]
The [Graylog 2.0 documentation](http://docs.graylog.org/en/2.0/pages/installation.html) requires Elasticsearch 2.1.x or later while it also advises to add `script.disable_dynamic: true` to the `elasticsearch.yml` file [here](http://docs.graylog.org/en/2.0/pages/configuring_es.html#disable-dynamic-scripting). I did that using Elasticsearch 2.3.2 and it resulted in error:

```
Exception in thread "main" java.lang.IllegalArgumentException: script.disable_dynamic is not a supported setting, replace with fine-grained script settings. 
Dynamic scripts can be enabled for all languages and all operations by replacing `script.disable_dynamic: false` with `script.inline: on` and `script.indexed: on` in elasticsearch.yml
```

[This issue](https://github.com/elastic/elasticsearch/issues/13756) says that such an error is thrown from ElasticSearch 2.x branch up. ElasticSearch docs on this topic are [here](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/modules-scripting.html#_disabling_dynamic_scripts). I am not sure if setting the most secure options:

```
script.inline: false
script.indexed: false
script.file: false
```

 won't hinder Graylog communication to ElasticSearch, so I can't suggest specific values, but definitely that part of Graylog documentation should be updated.

For me it would be enough if the documentation said: "Make sure to add `script.disable_dynamic: true` to the `elasticsearch.yml` file if you use ElasticSearch <2.0 ..."

**Comment by joschi** [comment]
@xmik Thanks! I've updated the paragraph about dynamic scripting in Elasticsearch.
