### ISSUE TITLE
Not existing image

### ISSUE THREAD

**Issue by Alexilmarranen** [Graylog2/documentation#78]
In documentation/pages/installation/docker.rst "graylog-server" image on Docker-hub not-exist.
![graylog-docker](https://cloud.githubusercontent.com/assets/3368275/15185872/7dbc6f36-17a3-11e6-8e0a-ac642ad0d860.png)

**Comment by joschi** [comment]
@Alexilmarranen The image is definitely there (https://hub.docker.com/r/graylog2/server/) but you have to use the fully qualified image name if you didn't download it before (i. e. `graylog2/server`).

Also see https://docs.docker.com/v1.8/userguide/dockerimages/#getting-a-new-image for instructions about how to fetch Docker images from the Docker Hub.

**Comment by joschi** [comment]
Wait, I've misread that. The image name is definitely wrong and should be `graylog2/server`.

**Comment by mariussturm** [comment]
This is fixed in the docs now, thanks!
