### ISSUE TITLE
Update install instructions for Debian 10 buster

### ISSUE THREAD

**Issue by kroepke** [Graylog2/documentation#810]
## Context
Debian 10 seems to have some changes related to how to install MongoDB and how systemctl commands are run.
See https://community.graylog.org/t/debian-10-buster-installation/9734
https://docs.graylog.org/en/3.2/pages/installation/operating_system_packages.html
## Expected Content
Updated instructions for Debian 10.

## Your Environment

* Graylog Version: 3.2
* Operating System: Debian 10

**Comment by jalogisch** [comment]
the documentation is adjusted to debian 10
