### ISSUE TITLE
3.2 search missing search time lookups

### ISSUE THREAD

**Issue by asmodianx** [Graylog2/documentation#817]
## Context

After upgrade from 3.1 to 3.2, In search new v3,2 does not have search time lookups
## Expected Content

the lefthand doc needs to allow creation of searchtime lookups
## Your Environment

Graylog 3.2.2+2f9a628 on aux-graylog1 (Private Build 1.8.0_242 on Linux 4.15.0-88-generic)
* Graylog Version:
Graylog 3.2.2+2f9a628
* Elasticsearch Version:
 6.8.6
* MongoDB Version:
v4.0.16
* Operating System:
ubuntu 18.04 x64

* Browser version:
Firefox

**Comment by jalogisch** [comment]
he @asmodianx 

this is the documentation repo - could you please be a little more specific what you are missing? I do not understand what you mean by `search time lookups`.

thank you

**Comment by asmodianx** [comment]
My mistake, where would i file a report for a feature which ”existed before
In 3.1 and does not exist now.”

**Comment by jalogisch** [comment]
He @asmodianx 

in the Graylog server-repo: https://github.com/Graylog2/graylog2-server/issues

But could you please be a little more verbose what you mean, please.

**Comment by asmodianx** [comment]
Sorry for the confusion!
