### ISSUE TITLE
After upgrade from 3.1 to 3.2, In search new v3.2 fields not limiting fields to what current search displays.  

### ISSUE THREAD

**Issue by asmodianx** [Graylog2/documentation#818]
## Context

After upgrade from 3.1 to 3.2, In search new v3.2 fields not limiting fields to what current search displays.  
## Expected Content

the lefthand doc needs to limit fields to what the current search contains
## Your Environment

Graylog 3.2.2+2f9a628 on aux-graylog1 (Private Build 1.8.0_242 on Linux 4.15.0-88-generic)
* Graylog Version:
Graylog 3.2.2+2f9a628
* Elasticsearch Version:
 6.8.6
* MongoDB Version:
v4.0.16
* Operating System:
ubuntu 18.04 x64

* Browser version:
Firefox

**Comment by jalogisch** [comment]
@asmodianx 

could it be that you want to have this issue as feature request in the Graylog server repo? The given context does not make sense in the documentation repo - but I might be wrong and you can verify and reword your request to the docs.

Jan

**Comment by asmodianx** [comment]
My mistake, where would i file a report for a feature which ”existed before
In 3.1 and does not exist now.”

**Comment by jalogisch** [comment]
He @asmodianx 

in the Graylog server-repo: https://github.com/Graylog2/graylog2-server/issues

But could you please be a little more verbose what you mean, please.

**Comment by asmodianx** [comment]
Sorry for the confusion!

**Comment by dennisoelkers** [comment]
There is an issue for this already: Graylog2/graylog2-server#7517.
