### ISSUE TITLE
log level appears different in web-ui 

### ISSUE THREAD

**Issue by ghost** [Graylog2/documentation#82]
Hi
When I send a log with default level { 0 or 5} it shows different log level in Graylog-web
Note

```
we use ruby module -- gelf notifier 
```

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog and its related projects, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
