### ISSUE TITLE
docker-compose examples don't survive reboot

### ISSUE THREAD

**Issue by rbarrette** [Graylog2/documentation#845]
The Docker issues page might be a more appropriate place for this bug, but I figure posting here could at least lead to a redesign of the docker-compose examples to avoid the issue described below.

## Context

Both V2/V3 Docker compose examples seem to run into an issue when attempting to invoke docker-compose up after reboot. 

After a reboot - the following error is displayed when invoking docker-compose up
rbarrette@mercury:/data/docker/greylog$ docker-compose up -d
ERROR: readlink /var/snap/docker/common/var-lib-docker/overlay2/l: invalid argument

I am able to fix the issue by going though the following steps outlined in [this](https://github.com/docker/for-mac/issues/1396#issuecomment-316330338)
similar issue.

## Expected Content

Consider redesign of docker-compose implementation to withstand non graceful restarts of docker daemon

## Your Environment

Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-91-generic x86_64)
Docker version 19.03.6, build 369ce74a3c

* Graylog Version:  graylog:3.2
* Elasticsearch Version: elasticsearch-oss:6.8.5
* MongoDB Version: mongo:3
* Operating System:Ubuntu 18.04

Thanks for your time!

**Comment by jalogisch** [comment]
I was not able to reproduce this problem and I can't think how to change the `docker-compose` file to not run into this. 

If possible, please re-open the issue and provide more information how this could reproduced OR how the compose file need to be modified to avoid this.

thank you
