### ISSUE TITLE
datatype conversion 

### ISSUE THREAD

**Issue by zhou-mfk** [Graylog2/documentation#85]
hello, 
I have a problem when I use graylog 
Is that when I want to use the data type conversion when there was a problem. 
This page has introduced about how to make data type conversion, http://docs.graylog.org/en/2.0/pages/extractors.html 
The page wrote:
Grok directly supports converting field values by adding ;datatype at the end of the pattern, like:

len=%{NUMBER:length;int} src=%{IP:srcip} sport=%{NUMBER:srcport} dst=%{IP:dstip} dport=%{NUMBER:dstport}

I write configuration is as follows: 
%{NUMBER:byes;int}

but,I found the conversion is not successful !!!
The field is not of type int.
When I try to use the "Generate chart" drawing, tip: 
    Could not create field graph
    Field graphs are only available for numeric fields.

I don't know what to do, I don't know why can't the converted format correct drawing.
I need your help! Please

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
