### ISSUE TITLE
Event notification documentation is outdated

### ISSUE THREAD

**Issue by mpfz0r** [Graylog2/documentation#870]
The documentation does not match the new alerting system we've introduced with 3.1.

Specifically the email templates has changed completely and is wrong:
 https://docs.graylog.org/en/3.2/pages/alerts.html#email-alert-notification

The http notification also needs an update to reflect the changed format.

**Comment by jalogisch** [comment]
https://github.com/Graylog2/documentation/pull/876 has closed this
