### ISSUE TITLE
Add section about creating custom Elasticsearch index mappings

### ISSUE THREAD

**Issue by joschi** [Graylog2/documentation#89]
https://www.elastic.co/guide/en/elasticsearch/reference/2.3/mapping.html
https://www.elastic.co/guide/en/elasticsearch/reference/2.3/indices-templates.html

**Comment by jalogisch** [comment]
should be closed with https://github.com/Graylog2/documentation/commit/1bd3421ce9b2644575547fea24d32fef7733fc30 or?
