### ISSUE TITLE
switch (-) missing in the README file of greylog-setup-1.0.0

### ISSUE THREAD

**Issue by sivasamyk** [Graylog2/documentation#9]
In the README file of greylog-setup-1.0.0, in "Graylog Server" section following command is missing a "-" switch for XX:+CMSConcurrentMTEnabled. 

 java -Xms1g -Xmx1g -XX:PermSize=128m -XX:MaxPermSize=256m -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC **XX:+CMSConcurrentMTEnabled** -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow -Djava.net.preferIPv4Stack=true -Djava.library.path=lib/sigar -jar graylog/graylog.jar server -p run/graylog.pid -f conf/graylog.conf

**Comment by joschi** [comment]
Thank you very much for reporting this! I've added the missing dash in the graylog-setup project and the fixed README will be contained in the next release.
