### ISSUE TITLE
Enabling HTTPS on AWS command not working

### ISSUE THREAD

**Issue by websoft** [Graylog2/documentation#98]
The [https section in the aws installation](http://docs.graylog.org/en/latest/pages/installation/aws.html#https) has the following command:

`sudo graylog-ctl https://<public ip>:443/api`

But that command seems not to be valid. It results in: "I don't know that command."

I am running graylog version 2

**Comment by joschi** [comment]
This has been fixed in #97 and is online at http://docs.graylog.org/en/latest/pages/installation/aws.html#https
